#!/bin/sh
# Say hello
echo ArcSight Internal RegUtility

#if [ "X$ARCSIGHT_HOME"=="X"]
#then
#    echo ERROR: Set ARCSIGHT_HOME before running this script.
#    exit
#fi

pwd

#dont change here , we add environment here
if [ ! -f ./arcsightenv.sh ]; then
#       Change to arcsight home folder
        # assume this is running from arcsight home (since this is only supposed to run from the configuration tool)
        ARCSIGHT_HOME=.
        JAVA_HOME=./jre
        export ARCSIGHT_HOME
        export JAVA_HOME
else
. ./arcsightenv.sh
fi


cd "$ARCSIGHT_HOME"

pwd

# ============================================================
# Set the Arcsight M3 classpath.
# ============================================================
CLASSPATH=
CLASSPATH=$CLASSPATH:lib/old/regv11.jar

CLASSPATH=$CLASSPATH:lib/old/agentframeworklib.jar
CLASSPATH=$CLASSPATH:lib/agent/jce1_2_2.jar
CLASSPATH=$CLASSPATH:lib/agent/sunjce_provider.jar
CLASSPATH=$CLASSPATH:lib/agent/US_export_policy.jar
CLASSPATH=$CLASSPATH:lib/agent/local_policy.jar
CLASSPATH=$CLASSPATH:lib/agent/j2ee.jar

export CLASSPATH

# ============================================================
# Start the console.
# ============================================================
$JAVA_HOME/bin/java $ARCSIGHT_JVM_OPTIONS -DARCSIGHT_HOME="$ARCSIGHT_HOME" -Djava.security.policy=="$ARCSIGHT_HOME"/lib/security/arcsight.policy com.arcsight.agent.configtool.ConfigTool "$@"

