cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/003_Safety_First/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/AdminWS/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/CCA/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/CMR/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/CmsWS/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/CPO/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/CWT/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/DefaultAppPool/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/EAA/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/EAF/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/ECR/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/ELMS/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/Forms/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/HeerOnline/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/InstantActivationWS/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/IQP/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/MAP/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/ONC/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/Outage/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SDP/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/Sears/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SMA/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SSOP/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/StatusInquiry/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/WfcWS/PeriodicRestartTime" 0
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/smaWs/AppPoolQueueLength" 4000
cscript "e:\temp\jr\adsutil.vbs" set "/w3svc/apppools/Sma/MaxProcesses" 3