cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/ActivationWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/CcaWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/ClaimsWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/cpows/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/CwtWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/DefaultAppPool/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/EafWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/EALC/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/EAWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/EcrWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/ElmsWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/FormsWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/FxWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/HeerWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/IqpWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/LOTUCIMS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/OncWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SC3RemoteApp/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SCEClaimServices/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SdpWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SearsWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SmaWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/SsopWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/StatusInquiryWS/PeriodicRestartTime" 0
cscript "E:\temp\jr\adsutil.vbs" set "/w3svc/apppools/WfcAppWS/PeriodicRestartTime" 0